### ISSUE TITLE
No static method AlertDialog - missing dependency? Material3 issue?

### ISSUE THREAD

**Issue by TheAlexSannikov** [lampione/ComposeCalendar#8]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/56170988/192933660-cc043971-c0ab-47e3-a143-c25f9dc934ce.png">

Here line 84 is where ComposeCalendar is called.

It's confusing - I can create an AlertDialog on its own, but I get this error when using ComposeCalendar.

The above error is when I paste your sample code into a material design 3 project; it seemed to work when I pasted it into a material design 2 project.

**Comment by sproctor** [comment]
It might be an issue with a mismatched version of the Compose Material 3 library since the one used here is still in alpha. Try 1.0.0-alpha14 and see if that resolves the issue. Otherwise, I've made a fork that drops the `AlertDialog` usage if you want to give that a try. https://github.com/sproctor/ComposeCalendar/tree/date_input I'll upload it to maven central later today.

**Comment by lampione** [comment]
This should've been fixed in v1.1.0 now.
